### ISSUE TITLE
bitsy 3d

### ISSUE THREAD

**Issue by zartan9** [aloelazoe/bitsy-3d#1]
hi im new here i have game idea... how can i make a box a wall/blocker (or do i use tower for that?) is pushing boxes possible wit bitsy3d? Thanks

**Comment by aloelazoe** [comment]
hi! replying late because i didn't get notified about this for some reason. in case you still need an answer. there is a "wall" button in the paint panel, check it to make any tile impassible. it can be represented by any 3d shape.
in the future, please keep in mind that github issues are for keeping track of bugs in the editor, they aren't a proper place to ask for advice. best place to ask about how something works is bitsy discord.
